# -*- coding: utf-8 -*-
"""VideoMAEMaskedonmChroMagic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fk-CDeP0AqZU8_q-OAcsxJkidgjY3HOq
"""

!pip install -q git+https://github.com/huggingface/transformers
!pip install -q torchcodec einops umap-learn scikit-learn matplotlib seaborn huggingface_hub av
print('Done.')

import math, copy, random, json, warnings
from pathlib import Path
from collections import defaultdict

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import seaborn as sns
import imageio
import av
from PIL import Image
from IPython.display import HTML, display

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from transformers import VideoMAEImageProcessor, VideoMAEModel
from transformers import AutoModel
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.metrics import accuracy_score, r2_score, confusion_matrix
from sklearn.preprocessing import StandardScaler

warnings.filterwarnings('ignore')
random.seed(42); np.random.seed(42)
torch.manual_seed(42); torch.cuda.manual_seed_all(42)

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device : {DEVICE}')
if DEVICE.type == 'cuda':
    print(f'GPU    : {torch.cuda.get_device_name(0)}')
    print(f'VRAM   : {torch.cuda.get_device_properties(0).total_memory/1e9:.1f} GB')

from huggingface_hub import hf_hub_download
from pathlib import Path
import zipfile
import random
import os

BENCH_ROOT = Path('/content/ChronoMagic-Bench')
BENCH_ROOT.mkdir(exist_ok=True)

# Step 1: Download ONLY the reference videos zip
zip_path = hf_hub_download(
    repo_id="BestWishYsh/ChronoMagic-Bench",
    repo_type="dataset",
    filename="Videos/Reference_Videos.zip",
    local_dir=BENCH_ROOT,
    local_dir_use_symlinks=False
)

print(f"Downloaded: {zip_path}")

# Step 2: Open zip and list files
with zipfile.ZipFile(zip_path, 'r') as z:
    all_videos = [f for f in z.namelist() if f.endswith('.mp4')]

print(f"Total videos inside zip: {len(all_videos)}")

# Step 3: Select 1/3
subset = random.sample(all_videos, len(all_videos)//4)

# Step 4: Extract only subset
extract_path = BENCH_ROOT / "videos_subset"
extract_path.mkdir(exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as z:
    for file in subset:
        z.extract(file, extract_path)

print(f"Extracted {len(subset)} videos")

csv_files = [
    "Captions/ChronoMagic-Bench.csv",
    "Captions/ChronoMagic-Bench-150.csv"
]

for csv_file in csv_files:
    hf_hub_download(
        repo_id="BestWishYsh/ChronoMagic-Bench",
        repo_type="dataset",
        filename=csv_file,
        local_dir=BENCH_ROOT,
        local_dir_use_symlinks=False
    )

print("Downloaded caption CSV files.")

BENCH_ROOT   = Path('/content/ChronoMagic-Bench')
VIDEO_SUBSET = BENCH_ROOT / 'videos_subset'
CAPTION_DIR  = BENCH_ROOT / 'Captions_subset'
CAPTION_DIR.mkdir(exist_ok=True)


mp4_files = list(VIDEO_SUBSET.rglob('*.mp4'))
print(f'mp4 files found in videos_subset: {len(mp4_files)}')
print(f'Sample paths:')
for f in mp4_files[:5]:
    print(f'  {f.relative_to(VIDEO_SUBSET)}')

stem_to_path = {f.stem: f for f in mp4_files}
print(f'\nUnique video stems: {len(stem_to_path)}')



csv_candidates = [
    BENCH_ROOT / 'ChronoMagic-Bench.csv',
    BENCH_ROOT / 'Captions' / 'ChronoMagic-Bench.csv',
]
full_csv_path = next((p for p in csv_candidates if p.exists()), None)

if full_csv_path is None:
    print('CSV not found locally — downloading from HuggingFace ...')
    for repo_filename in ('ChronoMagic-Bench.csv',
                          'Captions/ChronoMagic-Bench.csv',
                          'ChronoMagic_Bench.csv'):
        try:
            local = hf_hub_download(
                repo_id   = 'BestWishYsh/ChronoMagic-Bench',
                repo_type = 'dataset',
                filename  = repo_filename,
                local_dir = str(BENCH_ROOT),
                local_dir_use_symlinks = False,
            )
            full_csv_path = Path(local)
            print(f'Downloaded: {full_csv_path}')
            break
        except Exception:
            continue

if full_csv_path is None:
    raise FileNotFoundError(
        'Could not find ChronoMagic-Bench.csv. '
        'Place it manually at /content/ChronoMagic-Bench/ChronoMagic-Bench.csv'
    )

full_df = pd.read_csv(full_csv_path)
print(f'Full CSV  : {len(full_df)} rows  |  columns: {list(full_df.columns)}')



full_df['videoid_str'] = full_df['videoid'].astype(str).str.strip()

subset_df = full_df[full_df['videoid_str'].isin(stem_to_path)].copy()
subset_df = subset_df.reset_index(drop=True)

subset_df['resolved_path'] = subset_df['videoid_str'].apply(
    lambda v: str(stem_to_path[v])
)

subset_df['main_category'] = subset_df['main_category'].str.lower().str.strip()
subset_df['sub_category']  = subset_df['sub_category'].str.lower().str.strip()

subset_df_save = subset_df.drop(columns=['videoid_str'])

SUBSET_CSV = CAPTION_DIR / 'ChronoMagic-Bench_subset.csv'
subset_df_save.to_csv(SUBSET_CSV, index=False)

print(f'Subset CSV saved : {SUBSET_CSV}')
print(f'Rows             : {len(subset_df)}')
print(f'Unmatched videos : {len(stem_to_path) - len(subset_df)} '
      f'(in folder but not in CSV — normal for extra files)')
print()
print('main_category distribution:')
print(subset_df['main_category'].value_counts().to_string())
print()
print(f'sub_categories present : {subset_df["sub_category"].nunique()}')
print(subset_df[['videoid','main_category','sub_category']].head(6).to_string())

subset_df = subset_df.dropna(subset=['main_category'])

MAIN_CATS   = sorted(subset_df['main_category'].unique().tolist())
MAIN_TO_IDX = {c: i for i, c in enumerate(MAIN_CATS)}
IDX_TO_MAIN = {i: c for c, i in MAIN_TO_IDX.items()}
N_MAIN      = len(MAIN_CATS)
print(f'Main categories : {MAIN_CATS}')

MAX_FRAMES = 32
IMG_SIZE   = 128


def decode_frames(video_path, max_frames=32, img_size=128):
    """
    Uniformly sample up to max_frames from a video via PyAV.
    Returns (T, 3, H, W) float32 tensor in [-1, 1], or None on failure.
    """
    frames = []
    try:
        container = av.open(str(video_path))
        stream    = container.streams.video[0]
        total     = stream.frames or 0
        stride    = max(1, total // max_frames) if total > 0 else 1
        for i, frame in enumerate(container.decode(video=0)):
            if total > 0 and i % stride != 0:
                continue
            img = frame.to_image().convert('RGB')
            img = img.resize((img_size, img_size), Image.BILINEAR)
            arr = np.array(img, dtype=np.float32) / 127.5 - 1.0
            frames.append(arr)
            if len(frames) >= max_frames:
                break
        container.close()
    except Exception:
        return None
    if len(frames) < 2:
        return None
    return torch.tensor(np.stack(frames).transpose(0, 3, 1, 2))  # (T,3,H,W)


print(f'Decoding {len(subset_df)} videos at {IMG_SIZE}×{IMG_SIZE}, {MAX_FRAMES} frames each ...')
video_cache = []
failed = 0

for _, row in subset_df.iterrows():
    frames = decode_frames(row['resolved_path'], MAX_FRAMES, IMG_SIZE)
    if frames is None:
        failed += 1
        continue
    video_cache.append({
        'frames'      : frames,
        'main_cat'    : row['main_category'],
        'sub_cat'     : row['sub_category'],
        'main_cat_idx': MAIN_TO_IDX[row['main_category']],
        'caption'     : str(row['name']),
    })
    if len(video_cache) % 100 == 0:
        print(f'  {len(video_cache)} decoded  ({failed} failed)')

print(f'\nCache: {len(video_cache)} videos  ({failed} failed/corrupt)')
for cat in MAIN_CATS:
    n = sum(1 for v in video_cache if v['main_cat'] == cat)
    print(f'  {cat:22s}: {n}')

shown = {}
if len(video_cache) > 0:
    fig, axes = plt.subplots(N_MAIN, 4, figsize=(14, 3.5 * N_MAIN))
    if N_MAIN == 1: axes = axes[None, :]
    for vid in video_cache:
        cat = vid['main_cat']
        if cat in shown: continue
        shown[cat] = True
        ri = MAIN_TO_IDX[cat]
        T  = vid['frames'].shape[0]
        for ci, fi in enumerate(np.linspace(0, T-1, 4, dtype=int)):
            img = np.clip((vid['frames'][fi].permute(1,2,0).numpy()+1)/2, 0, 1)
            axes[ri, ci].imshow(img)
            axes[ri, ci].set_title(f'{cat}  t={fi}', fontsize=8)
            axes[ri, ci].axis('off')
        if len(shown) == N_MAIN: break

    Path('/content/results').mkdir(exist_ok=True)
    plt.suptitle('Sample frames per category', fontsize=12, fontweight='bold')
    plt.tight_layout()
    plt.savefig('/content/results/sample_frames.png', dpi=150, bbox_inches='tight')
    plt.show()



MODEL_ID   = 'MCG-NJU/videomae-base'
N_FRAMES   = 16    # VideoMAE-base expects exactly 16 frames
IMG_SIZE   = 224

print(f'Loading {MODEL_ID} ...')
processor = VideoMAEImageProcessor.from_pretrained(MODEL_ID)
vmae      = VideoMAEModel.from_pretrained(MODEL_ID).to(DEVICE).eval()
for p in vmae.parameters(): p.requires_grad_(False)


dummy_frames = [np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.uint8)] * N_FRAMES
inputs = processor(dummy_frames, return_tensors='pt')
pv     = inputs['pixel_values'].to(DEVICE)   # (1, T, C, H, W)

with torch.no_grad():
    out = vmae(pixel_values=pv)

# last_hidden_state: (1, N_tok, D)
# N_tok = (T / tubelet_size) × (H/patch)² = (16/2) × 14² = 8 × 196 = 1568
N_TOK  = out.last_hidden_state.shape[1]   # 1568
ENC_D  = out.last_hidden_state.shape[2]   # 768 for ViT-B

# Patches per frame = N_TOK / (T / tubelet_size)
TUBELET      = vmae.config.tubelet_size          # 2
N_TIME       = N_FRAMES // TUBELET              # 8 temporal positions
PATCHES_PER_T = (vmae.config.image_size // vmae.config.patch_size) ** 2  # 196

print(f'Token sequence length : {N_TOK}  ({N_TIME} temporal × {PATCHES_PER_T} spatial)')
print(f'Embedding dim         : {ENC_D}')
print(f'Tubelet size          : {TUBELET}')
print(f'VRAM after load       : {torch.cuda.memory_allocated()/1e9:.2f} GB')

def decode_clip(video_path, n_frames=16, img_size=224):
    """
    Uniformly sample n_frames from a video.
    Returns list of PIL RGB Images (required by VideoMAEImageProcessor),
    or None on failure.
    """
    frames = []
    try:
        container = av.open(str(video_path))
        stream    = container.streams.video[0]
        total     = stream.frames or 0
        stride    = max(1, total // n_frames) if total > 0 else 1
        for i, frame in enumerate(container.decode(video=0)):
            if total > 0 and i % stride != 0: continue
            img = frame.to_image().convert('RGB').resize(
                (img_size, img_size), Image.BILINEAR
            )
            frames.append(img)
            if len(frames) >= n_frames: break
        container.close()
    except Exception:
        return None

    while len(frames) < n_frames:
        frames.append(frames[-1])
    return frames[:n_frames]   # list of n_frames PIL Images


FEAT_PATH = Path('/content/vmae_feat_cache.pt')


@torch.no_grad()
def encode_video(video_path):
    """
    Returns (N_TOK, ENC_D) float32 token sequence, or None on failure.
    """
    frames = decode_clip(video_path, n_frames=N_FRAMES, img_size=IMG_SIZE)
    if frames is None: return None

    inputs = processor(frames, return_tensors='pt')
    pv     = inputs['pixel_values'].to(DEVICE)   # (1, T, C, H, W)

    out    = vmae(pixel_values=pv)
    tokens = out.last_hidden_state.squeeze(0).cpu().float()  # (N_TOK, D)
    return tokens


if FEAT_PATH.exists():
    print('Loading cached VideoMAE features ...')
    feat_cache = torch.load(FEAT_PATH)
    print(f'Loaded {len(feat_cache)} entries.')
else:
    print(f'Extracting features for {len(subset_df)} videos ...')
    feat_cache = []
    n_fail     = 0

    for _, row in subset_df.iterrows():
        tokens = encode_video(row['resolved_path'])
        if tokens is None:
            n_fail += 1; continue

        feat_cache.append({
            'tokens'      : tokens,                         # (N_TOK, D)
            'main_cat'    : row['main_category'],
            'sub_cat'     : row['sub_category'],
            'main_cat_idx': MAIN_TO_IDX[row['main_category']],
            'videoid'     : str(row['videoid']),
        })

        if len(feat_cache) % 100 == 0:
            print(f'  {len(feat_cache)} done  ({n_fail} failed)')
            torch.cuda.empty_cache()

    torch.save(feat_cache, FEAT_PATH)
    print(f'Saved. Failures: {n_fail}')

ex = feat_cache[0]
print(f'Token shape : {ex["tokens"].shape}  (N_TOK={N_TOK}, D={ENC_D})')
norms = ex['tokens'].norm(dim=-1)
print(f'Token norms : min={norms.min():.2f}  mean={norms.mean():.2f}  max={norms.max():.2f}')


CTX_FRAC   = 0.5    # fraction of temporal positions used as context
MASK_RATIO = 0.75   # fraction of context tokens that are masked

CTX_T  = max(1, int(N_TIME * CTX_FRAC))   # context temporal positions
TGT_T  = N_TIME - CTX_T                   # target temporal positions
CTX_N  = CTX_T * PATCHES_PER_T            # context token count
TGT_N  = TGT_T * PATCHES_PER_T            # target token count
N_MASK = int(CTX_N * MASK_RATIO)          # masked context tokens
N_VIS  = CTX_N - N_MASK                   # visible context tokens

print(f'Total tokens          : {N_TOK}')
print(f'Context tokens (CTX_N): {CTX_N}  ({CTX_T} temporal × {PATCHES_PER_T} spatial)')
print(f'Target  tokens (TGT_N): {TGT_N}  ({TGT_T} temporal × {PATCHES_PER_T} spatial)')
print(f'Masked context tokens : {N_MASK}  (mask_ratio={MASK_RATIO})')
print(f'Visible context tokens: {N_VIS}')


class LatentMaskVideoDataset(Dataset):
    """
    Each sample:
      vis_tokens  : (N_VIS, D)  — visible (unmasked) context tokens
      vis_ids     : (N_VIS,)    — their positions in the full sequence
      mask_tokens : (N_MASK, D) — masked context tokens (reconstruction targets)
      mask_ids    : (N_MASK,)   — their positions
      tgt_tokens  : (TGT_N, D)  — all target frame tokens (future prediction targets)
      main_cat    : int
    """

    def __init__(self, cache, samples_per_video=8):
        self.cache            = cache
        self.samples_per_video = samples_per_video
        self._build_index()

    def _build_index(self):
        self.samples = []
        for vi in range(len(self.cache)):
            for _ in range(self.samples_per_video):
                self.samples.append(vi)
        random.shuffle(self.samples)

    def __len__(self): return len(self.samples)

    def __getitem__(self, idx):
        vi      = self.samples[idx]
        e       = self.cache[vi]
        tokens  = e['tokens']   # (N_TOK, D)

        # Split into context and target along temporal axis
        ctx_all = tokens[:CTX_N]   # (CTX_N, D)
        tgt_all = tokens[CTX_N:]   # (TGT_N, D)

        # Random latent mask on context tokens
        perm     = torch.randperm(CTX_N)
        vis_ids  = perm[N_MASK:].sort().values   # (N_VIS,)
        mask_ids = perm[:N_MASK].sort().values   # (N_MASK,)

        vis_tokens  = ctx_all[vis_ids]    # (N_VIS, D)
        mask_tokens = ctx_all[mask_ids]   # (N_MASK, D)  ground truth for reconstruction

        return {
            'vis_tokens'  : vis_tokens,
            'vis_ids'     : vis_ids,
            'mask_tokens' : mask_tokens,
            'mask_ids'    : mask_ids,
            'tgt_tokens'  : tgt_all,
            'main_cat'    : e['main_cat_idx'],
            'sub_cat'     : e['sub_cat'],
        }


# Stratified train / val split
by_cat = defaultdict(list)
for i, e in enumerate(feat_cache): by_cat[e['main_cat']].append(i)
train_idx, val_idx = [], []
for cat, idxs in by_cat.items():
    random.shuffle(idxs)
    n = int(0.8 * len(idxs))
    train_idx.extend(idxs[:n]); val_idx.extend(idxs[n:])

train_fc = [feat_cache[i] for i in train_idx]
val_fc   = [feat_cache[i] for i in val_idx]

train_ds = LatentMaskVideoDataset(train_fc, samples_per_video=8)
val_ds   = LatentMaskVideoDataset(val_fc,   samples_per_video=4)

train_loader = DataLoader(train_ds, batch_size=16, shuffle=True,
                          num_workers=2, pin_memory=True, drop_last=True)
val_loader   = DataLoader(val_ds,   batch_size=16, shuffle=False,
                          num_workers=2, pin_memory=True)

print(f'\nTrain videos : {len(train_fc)} | Val videos : {len(val_fc)}')
print(f'Train samples: {len(train_ds)} | Val samples: {len(val_ds)}')
print(f'Steps/epoch  : {len(train_loader)}')

# Verify batch shapes
b = next(iter(train_loader))
print(f'\nBatch vis_tokens  : {b["vis_tokens"].shape}   (B, N_VIS, D)')
print(f'Batch mask_tokens : {b["mask_tokens"].shape}  (B, N_MASK, D)')
print(f'Batch tgt_tokens  : {b["tgt_tokens"].shape}   (B, TGT_N, D)')

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=2048):
        super().__init__()
        pe  = torch.zeros(max_len, d_model)
        pos = torch.arange(max_len).unsqueeze(1).float()
        div = torch.exp(torch.arange(0, d_model, 2).float() *
                        (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(pos * div)
        pe[:, 1::2] = torch.cos(pos * div[:d_model//2])
        self.register_buffer('pe', pe)   # (max_len, d)

    def forward(self, ids):
        """ids: (B,N) position indices"""
        return self.pe[ids, :]


class LatentMaskPredictor(nn.Module):

    def __init__(self, enc_dim, pred_dim, n_heads, n_layers,
                 n_vis, n_mask, n_tgt):
        super().__init__()
        self.n_vis   = n_vis
        self.n_mask  = n_mask
        self.n_tgt   = n_tgt
        self.pred_dim = pred_dim

        # Input projection
        self.in_proj = nn.Linear(enc_dim, pred_dim)

        # Learnable tokens for masked positions and future positions
        self.mask_token   = nn.Parameter(torch.randn(1, 1, pred_dim) * 0.02)
        self.future_token = nn.Parameter(torch.randn(1, 1, pred_dim) * 0.02)

        # Positional encoding over the full sequence
        self.pos_enc = PositionalEncoding(pred_dim, max_len=CTX_N + TGT_N + 16)

        # Shared transformer encoder (attends globally over all tokens)
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=pred_dim, nhead=n_heads,
            dim_feedforward=pred_dim * 4,
            dropout=0.0, batch_first=True, norm_first=True
        )
        self.transformer = nn.TransformerEncoder(encoder_layer,
                                                  num_layers=n_layers)
        self.norm = nn.LayerNorm(pred_dim)

        # Separate output heads for reconstruction and future prediction
        self.recon_head  = nn.Linear(pred_dim, enc_dim)
        self.future_head = nn.Linear(pred_dim, enc_dim)

        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.trunc_normal_(m.weight, std=0.02)
                if m.bias is not None: nn.init.zeros_(m.bias)

    def forward(self, vis_tokens, vis_ids, mask_ids):
        """
        vis_tokens : (B, N_VIS, enc_dim)  — visible context tokens
        vis_ids    : (B, N_VIS)           — their sequence positions
        mask_ids   : (B, N_MASK)          — masked positions (to reconstruct)

        Returns:
          recon_pred  : (B, N_MASK, enc_dim)  predicted masked context tokens
          future_pred : (B, N_TGT,  enc_dim)  predicted target frame tokens
        """
        B = vis_tokens.shape[0]

        # 1. Project visible tokens and add positional encoding
        vis = self.in_proj(vis_tokens)              # (B, N_VIS, pred_dim)
        vis = vis + self.pos_enc(vis_ids)           # Correctly get and add position

        # 2. Masked context tokens: learnable token + positional encoding
        mask_tok = self.mask_token.expand(B, self.n_mask, -1).clone()
        mask_tok = mask_tok + self.pos_enc(mask_ids) # Correctly get and add position

        # 3. Future tokens: learnable token + offset positional encoding
        future_positions = torch.arange(
            CTX_N, CTX_N + self.n_tgt, device=vis_tokens.device
        ).unsqueeze(0).expand(B, -1) # (B, TGT_N)
        fut_tok = self.future_token.expand(B, self.n_tgt, -1).clone()
        fut_tok = fut_tok + self.pos_enc(future_positions) # Correctly get and add position

        # 4. Concatenate all tokens: [visible | masked | future]
        x = torch.cat([vis, mask_tok, fut_tok], dim=1)  # (B, N_VIS+N_MASK+TGT_N, d)

        # 5. Transformer (global attention)
        x = self.norm(self.transformer(x))

        # 6. Read out predictions at the correct positions
        recon_out  = x[:, self.n_vis : self.n_vis + self.n_mask, :]  # masked ctx
        future_out = x[:, self.n_vis + self.n_mask:, :]              # future

        return self.recon_head(recon_out), self.future_head(future_out)


predictor = LatentMaskPredictor(
    enc_dim  = ENC_D,
    pred_dim = 512,
    n_heads  = 8,
    n_layers = 4,
    n_vis    = N_VIS,
    n_mask   = N_MASK,
    n_tgt    = TGT_N,
).to(DEVICE)

n_pred = sum(p.numel() for p in predictor.parameters())
print(f'Predictor parameters : {n_pred/1e6:.2f} M  (all trainable)')

# Smoke test
b      = next(iter(train_loader))
_vis   = b['vis_tokens'].to(DEVICE)
_vids  = b['vis_ids'].to(DEVICE)
_mids  = b['mask_ids'].to(DEVICE)
_r, _f = predictor(_vis, _vids, _mids)
print(f'Recon  pred shape : {_r.shape}  (B, N_MASK={N_MASK}, D={ENC_D})')
print(f'Future pred shape : {_f.shape}  (B, TGT_N={TGT_N},  D={ENC_D})')



def latent_mask_loss(recon_pred, recon_tgt,
                      future_pred, future_tgt,
                      lam_recon=1.0, lam_future=1.0):
    """
    recon_pred, recon_tgt   : (B, N_MASK, D)
    future_pred, future_tgt : (B, TGT_N, D)
    """
    B, Nm, D = recon_pred.shape
    Bt, Nt, _ = future_pred.shape

    # Flatten and normalise
    rp = F.normalize(recon_pred.reshape(B*Nm, D),  dim=-1)
    rt = F.normalize(recon_tgt.reshape(B*Nm, D),   dim=-1)
    fp = F.normalize(future_pred.reshape(Bt*Nt, D), dim=-1)
    ft = F.normalize(future_tgt.reshape(Bt*Nt, D),  dim=-1)

    recon_loss  = F.mse_loss(rp, rt)
    future_loss = F.mse_loss(fp, ft)

    total = lam_recon * recon_loss + lam_future * future_loss
    return total, {'recon': recon_loss.item(), 'future': future_loss.item()}

N_EPOCHS      = 60
BASE_LR       = 1e-4
WEIGHT_DECAY  = 1e-4
WARMUP_EPOCHS = 8

optimizer    = torch.optim.AdamW(predictor.parameters(),
                                  lr=BASE_LR, weight_decay=WEIGHT_DECAY)
total_steps  = N_EPOCHS * len(train_loader)
warmup_steps = WARMUP_EPOCHS * len(train_loader)

def lr_at(step):
    if step < warmup_steps:
        return BASE_LR * step / max(1, warmup_steps)
    p = (step - warmup_steps) / max(1, total_steps - warmup_steps)
    return 1e-6 + (BASE_LR - 1e-6) * 0.5 * (1 + math.cos(math.pi * p))


history     = defaultdict(list)
best_loss   = float('inf')
global_step = 0
Path('/content/checkpoints').mkdir(exist_ok=True)
Path('/content/results').mkdir(exist_ok=True)

for epoch in range(N_EPOCHS):
    predictor.train()
    train_ds._build_index()
    ep_loss  = 0.
    ep_comps = defaultdict(float)

    for batch in train_loader:
        vis  = batch['vis_tokens'].to(DEVICE)   # (B, N_VIS, D)
        vids = batch['vis_ids'].to(DEVICE)      # (B, N_VIS)
        mids = batch['mask_ids'].to(DEVICE)     # (B, N_MASK)
        mgt  = batch['mask_tokens'].to(DEVICE)  # (B, N_MASK, D) recon ground truth
        tgt  = batch['tgt_tokens'].to(DEVICE)   # (B, TGT_N, D) future ground truth

        for pg in optimizer.param_groups: pg['lr'] = lr_at(global_step)

        recon_pred, future_pred = predictor(vis, vids, mids)
        loss, comps = latent_mask_loss(recon_pred, mgt, future_pred, tgt)

        optimizer.zero_grad()
        loss.backward()
        nn.utils.clip_grad_norm_(predictor.parameters(), 1.0)
        optimizer.step()

        lv = loss.item()
        ep_loss += lv
        for k, v in comps.items(): ep_comps[k] += v
        global_step += 1

    n   = len(train_loader)
    avg = ep_loss / n
    history['epoch'].append(epoch)
    history['loss'].append(avg)
    history['lr'].append(lr_at(global_step))
    for k in ['recon', 'future']: history[k].append(ep_comps[k]/n)

    if epoch % 10 == 0 or epoch == N_EPOCHS-1:
        print(f'[{epoch:3d}/{N_EPOCHS}] loss={avg:.4f}  '
              f'recon={ep_comps["recon"]/n:.4f}  '
              f'future={ep_comps["future"]/n:.4f}  '
              f'lr={lr_at(global_step):.2e}')

    if avg < best_loss:
        best_loss = avg
        torch.save({'epoch': epoch, 'state': predictor.state_dict(),
                    'loss': avg},
                   '/content/checkpoints/best_latent_mask.pt')

print(f'\nDone. Best loss: {best_loss:.4f}')
print('Healthy: recon ~0.05–0.5, future ~0.1–0.8, total ~0.1–1.0')

ckpt = torch.load('/content/checkpoints/best_latent_mask.pt', map_location=DEVICE)
predictor.load_state_dict(ckpt['state'])
predictor.eval()
print(f"Best  epoch={ckpt['epoch']}  loss={ckpt['loss']:.4f}")


@torch.no_grad()
def extract_results_fixed(loader):
    """
    All residuals computed on L2-normalised token vectors → bounded in [0, 2].
    Cosine similarity computed both for the predictor and for the
    copy-context baseline (predict future = context mean, i.e. no change).
    """
    out = defaultdict(list)

    for batch in loader:
        vis  = batch['vis_tokens'].to(DEVICE)   # (B, N_VIS, D)
        vids = batch['vis_ids'].to(DEVICE)
        mids = batch['mask_ids'].to(DEVICE)
        mgt  = batch['mask_tokens'].to(DEVICE)  # (B, N_MASK, D)
        tgt  = batch['tgt_tokens'].to(DEVICE)   # (B, TGT_N, D)
        B, Nm, D = mgt.shape
        Nt = tgt.shape[1]

        recon_pred, future_pred = predictor(vis, vids, mids)


        rp_n = F.normalize(recon_pred.reshape(B*Nm, D), dim=-1).reshape(B, Nm, D)
        rt_n = F.normalize(mgt.reshape(B*Nm, D),        dim=-1).reshape(B, Nm, D)
        recon_res = (rp_n - rt_n).norm(dim=-1).mean(dim=-1)   # (B,) ∈ [0,2]


        fp_n = F.normalize(future_pred.reshape(B*Nt, D), dim=-1).reshape(B, Nt, D)
        ft_n = F.normalize(tgt.reshape(B*Nt, D),          dim=-1).reshape(B, Nt, D)
        future_res = (fp_n - ft_n).norm(dim=-1).mean(dim=-1)  # (B,) ∈ [0,2]


        ctx_mean  = vis.mean(dim=1)           # (B, D)  mean over visible context patches
        tgt_mean  = tgt.mean(dim=1)           # (B, D)  mean over target patches
        pred_mean = future_pred.mean(dim=1)   # (B, D)  predictor's future estimate

        actual_dir = tgt_mean - ctx_mean      # actual displacement direction
        pred_dir   = pred_mean - ctx_mean     # predictor's displacement direction

        future_cos = F.cosine_similarity(pred_dir, actual_dir, dim=-1)  # (B,)

        # If actual_dir has zero norm (target ≈ context), cosine is undefined → 0.
        zero_dir   = torch.zeros_like(ctx_mean)  # predict no change
        copy_cos   = F.cosine_similarity(zero_dir, actual_dir, dim=-1)  # should be ~0


        improvement = future_cos - copy_cos    # >0 means predictor actually helps

        out['ctx_r'].append(ctx_mean.cpu().float().numpy())
        out['tgt_r'].append(tgt_mean.cpu().float().numpy())
        out['pred_r'].append(pred_mean.cpu().float().numpy())
        out['recon_res'].append(recon_res.cpu().numpy())
        out['future_res'].append(future_res.cpu().numpy())
        out['future_cos'].append(future_cos.cpu().numpy())
        out['copy_cos'].append(copy_cos.cpu().numpy())
        out['improvement'].append(improvement.cpu().numpy())
        out['main_cat'].append(batch['main_cat'].numpy())
        out['sub_cat'].append(np.array(batch['sub_cat']))

    return {k: np.concatenate(v) for k, v in out.items()}


R = extract_results_fixed(val_loader)
cat_vals  = R['main_cat']
cat_names = [IDX_TO_MAIN[i] for i in range(N_MAIN)]

print('─' * 55)
print('  Metrics in NORMALISED latent space  (range [0, 2])')
print('─' * 55)
print(f'  Mean recon residual    : {R["recon_res"].mean():.4f}')
print(f'  Mean future residual   : {R["future_res"].mean():.4f}')
print()
print('  Directional alignment:')
print(f'  Predictor cosine sim   : {R["future_cos"].mean():.4f}')
print(f'  Copy-context baseline  : {R["copy_cos"].mean():.4f}  (should be ~0)')
print(f'  Improvement over copy  : {R["improvement"].mean():.4f}  (want >0)')
print()
if R['improvement'].mean() > 0.05:
    print('  ✅ Predictor genuinely improves over copy-context baseline.')
elif R['improvement'].mean() > 0:
    print('  ⚠️  Marginal improvement — predictor is partially learning.')
else:
    print('  ❌ No improvement over copy-context — predictor learned nothing useful.')



@torch.no_grad()
def extract_one_per_video(feat_cache_split, predictor, device):
    """
    One representation per video — no repeated sampling.
    Uses a fixed deterministic mask (first N_MASK tokens masked).
    Returns X (n_videos, D), y_main, y_sub, videoids
    """
    X, y_main, y_sub, vids = [], [], [], []

    for e in feat_cache_split:
        tok = e['tokens']   # (N_TOK, D)

        ctx_all = tok[:CTX_N]   # (CTX_N, D)
        tgt_all = tok[CTX_N:]   # (TGT_N, D)

        vis_ids  = torch.arange(N_MASK, CTX_N)    # (N_VIS,)
        mask_ids = torch.arange(0, N_MASK)         # (N_MASK,)

        vis_tok  = ctx_all[vis_ids].unsqueeze(0).to(device)    # (1, N_VIS, D)
        vis_ids_ = vis_ids.unsqueeze(0).to(device)             # (1, N_VIS)
        msk_ids_ = mask_ids.unsqueeze(0).to(device)            # (1, N_MASK)

        _, future_pred = predictor(vis_tok, vis_ids_, msk_ids_)
        rep = future_pred.mean(dim=1).squeeze(0).cpu().float().numpy()  # (D,)

        X.append(rep)
        y_main.append(e['main_cat_idx'])
        y_sub.append(e['sub_cat'])
        vids.append(e['videoid'])

    return np.array(X), np.array(y_main), y_sub


predictor.eval()
print('Extracting one representation per video ...')
X_tr, y_tr, ys_tr = extract_one_per_video(train_fc, predictor, DEVICE)
X_va, y_va, ys_va = extract_one_per_video(val_fc,   predictor, DEVICE)

print(f'Train: {X_tr.shape}  Val: {X_va.shape}')
print(f'Val category distribution: {dict(zip(*np.unique(y_va, return_counts=True)))}')

# Scale
scaler = StandardScaler().fit(X_tr)
X_tr_s = scaler.transform(X_tr)
X_va_s = scaler.transform(X_va)

# Main category probe
clf = LogisticRegression(max_iter=500, C=1.0, multi_class='multinomial')
clf.fit(X_tr_s, y_tr)
acc = accuracy_score(y_va, clf.predict(X_va_s))
print(f'\nMain category accuracy : {acc*100:.1f}%  (random={100/N_MAIN:.1f}%)')
print('(This uses PREDICTED future representations, not raw encoder features)')

# Also probe on raw encoder features for comparison
def get_raw_reps(fc):
    return np.array([e['tokens'][CTX_N:].mean(dim=0).numpy() for e in fc])

X_raw_tr = StandardScaler().fit_transform(get_raw_reps(train_fc))
X_raw_va = StandardScaler().fit_transform(get_raw_reps(val_fc))
clf_raw  = LogisticRegression(max_iter=500, C=1.0, multi_class='multinomial')
clf_raw.fit(X_raw_tr, y_tr)
acc_raw = accuracy_score(y_va, clf_raw.predict(X_raw_va))
print(f'Raw encoder accuracy   : {acc_raw*100:.1f}%')
print(f'(If predictor acc > raw encoder acc, predictor added useful information)')

# Sub-category probe (on raw features — meaningful difficulty)
le   = {s: i for i, s in enumerate(sorted(set(ys_tr + ys_va)))}
ys_tr_i = np.array([le[s] for s in ys_tr])
ys_va_i = np.array([le[s] for s in ys_va])
clf2 = LogisticRegression(max_iter=500, C=0.1, multi_class='multinomial')
clf2.fit(X_raw_tr, ys_tr_i)
acc2 = accuracy_score(ys_va_i, clf2.predict(X_raw_va))
print(f'Sub-category accuracy  : {acc2*100:.1f}%  (random={100/len(le):.1f}%)')

# Confusion matrix
cm = confusion_matrix(y_va, clf.predict(X_va_s))
present = [cat_names[i] for i in sorted(set(y_va))]
fig, ax = plt.subplots(figsize=(7, 6))
sns.heatmap(cm, annot=True, fmt='d', ax=ax,
            xticklabels=present, yticklabels=present, cmap='Blues')
ax.set_xlabel('Predicted'); ax.set_ylabel('True')
ax.set_title(f'Category Confusion (predicted future reps)\nacc={acc*100:.1f}%  |  '
             f'one sample per video  |  n_val={len(y_va)}')
plt.tight_layout()
plt.savefig('/content/results/confusion_fixed.png', dpi=150, bbox_inches='tight')
plt.show()


fig, axes = plt.subplots(2, 3, figsize=(18, 10))

# A. Recon residual by category (normalised)
groups_r = [R['recon_res'][cat_vals==i] for i in range(N_MAIN) if (cat_vals==i).sum()>0]
labels_r = [cat_names[i] for i in range(N_MAIN) if (cat_vals==i).sum()>0]
axes[0,0].boxplot(groups_r, labels=labels_r, patch_artist=True)
axes[0,0].set(ylabel='Normalised residual ∈ [0,2]')
axes[0,0].set_title('Reconstruction Residual by Category')
axes[0,0].tick_params(axis='x', rotation=20); axes[0,0].grid(alpha=0.3)

# B. Future residual by category (normalised)
groups_f = [R['future_res'][cat_vals==i] for i in range(N_MAIN) if (cat_vals==i).sum()>0]
axes[0,1].boxplot(groups_f, labels=labels_r, patch_artist=True)
axes[0,1].set(ylabel='Normalised residual ∈ [0,2]')
axes[0,1].set_title('Future Prediction Residual by Category')
axes[0,1].tick_params(axis='x', rotation=20); axes[0,1].grid(alpha=0.3)

# C. Predictor improvement over copy-context baseline by category
groups_imp = [R['improvement'][cat_vals==i] for i in range(N_MAIN) if (cat_vals==i).sum()>0]
axes[0,2].boxplot(groups_imp, labels=labels_r, patch_artist=True)
axes[0,2].axhline(0, c='red', ls='--', lw=1.5, label='copy-context baseline')
axes[0,2].set(ylabel='Cosine sim improvement over copy-context')
axes[0,2].set_title('Predictor Improvement by Category\n'
                     '(>0 = predictor beats doing nothing)')
axes[0,2].tick_params(axis='x', rotation=20); axes[0,2].grid(alpha=0.3)
axes[0,2].legend()

# D. Predictor vs copy-context cosine comparison (violin)
axes[1,0].violinplot([R['copy_cos'], R['future_cos']],
                      positions=[0, 1], showmedians=True)
axes[1,0].set_xticks([0, 1])
axes[1,0].set_xticklabels(['Copy-context\nbaseline', 'Predictor'])
axes[1,0].set(ylabel='Cosine similarity with actual future direction')
axes[1,0].set_title('Predictor vs Copy-Context Baseline')
axes[1,0].axhline(0, c='gray', ls='--', lw=1); axes[1,0].grid(alpha=0.3)

# E. Improvement histogram
imp = R['improvement']
axes[1,1].hist(imp, bins=40, color='mediumseagreen', alpha=0.8, edgecolor='white')
axes[1,1].axvline(imp.mean(), c='red', lw=2, label=f'mean={imp.mean():.3f}')
axes[1,1].axvline(0, c='gray', lw=1.5, ls='--', label='no improvement')
axes[1,1].set(xlabel='Cosine sim improvement over copy-context')
axes[1,1].set_title('Distribution of Predictor Improvement')
axes[1,1].legend()

# F. Recon vs future residual
r_corr = np.corrcoef(R['recon_res'], R['future_res'])[0,1]
axes[1,2].scatter(R['recon_res'], R['future_res'], alpha=0.3, s=8, c='steelblue')
axes[1,2].set(xlabel='Reconstruction residual [0,2]',
               ylabel='Future prediction residual [0,2]')
axes[1,2].set_title(f'Recon vs Future Residual  r={r_corr:.3f}')
axes[1,2].grid(alpha=0.3)

plt.suptitle('Latent Masked Video Prediction — Fixed Evaluation',
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('/content/results/analysis_fixed.png', dpi=150, bbox_inches='tight')
plt.show()

X = StandardScaler().fit_transform(R['ctx_r'])
y = R['main_cat']
n = int(0.7 * len(X))

clf = LogisticRegression(max_iter=500, C=1.0, multi_class='multinomial')
clf.fit(X[:n], y[:n])
acc = accuracy_score(y[n:], clf.predict(X[n:]))
print(f'Main category accuracy : {acc*100:.1f}%  (random={100/N_MAIN:.1f}%)')

le   = {s: i for i, s in enumerate(sorted(set(R['sub_cat'])))}
ys   = np.array([le[s] for s in R['sub_cat']])
clf2 = LogisticRegression(max_iter=500, C=1.0, multi_class='multinomial')
clf2.fit(X[:n], ys[:n])
acc2 = accuracy_score(ys[n:], clf2.predict(X[n:]))
print(f'Sub-category accuracy  : {acc2*100:.1f}%  (random={100/len(le):.1f}%)')

# Confusion matrix for main categories
cm = confusion_matrix(y[n:], clf.predict(X[n:]))
present = [cat_names[i] for i in range(N_MAIN) if (y==i).sum()>0]
fig, ax = plt.subplots(figsize=(7, 6))
sns.heatmap(cm, annot=True, fmt='d', ax=ax,
            xticklabels=present, yticklabels=present, cmap='Blues')
ax.set_xlabel('Predicted'); ax.set_ylabel('True')
ax.set_title(f'Category Confusion  acc={acc*100:.1f}%')
plt.tight_layout()
plt.savefig('/content/results/confusion.png', dpi=150, bbox_inches='tight')
plt.show()

try:
    import umap

    # Build per-video frame embeddings for UMAP
    # Each video contributes N_TIME mean-pooled temporal positions
    all_vecs, all_cats, all_vids, all_times = [], [], [], []
    for vi, e in enumerate(val_fc):
        tok = e['tokens']   # (N_TOK, D)
        for ti in range(N_TIME):
            t_start = ti * PATCHES_PER_T
            t_end   = t_start + PATCHES_PER_T
            vec     = tok[t_start:t_end].mean(dim=0).numpy()   # (D,)
            all_vecs.append(vec)
            all_cats.append(e['main_cat_idx'])
            all_vids.append(vi)
            all_times.append(ti)

    all_vecs  = np.array(all_vecs)
    all_cats  = np.array(all_cats)
    all_vids  = np.array(all_vids)
    all_times = np.array(all_times)

    print(f'Fitting UMAP on {len(all_vecs)} temporal frame embeddings ...')
    reducer = umap.UMAP(n_neighbors=15, min_dist=0.1,
                        metric='cosine', random_state=42)
    emb = reducer.fit_transform(all_vecs)   # (N, 2)
    print('UMAP done.')

    cmap = plt.cm.tab10

    fig, ax = plt.subplots(figsize=(9, 7))
    for ci, cname in enumerate(cat_names):
        mask = all_cats == ci
        if mask.sum() == 0: continue
        ax.scatter(emb[mask,0], emb[mask,1], s=10, alpha=0.4,
                   color=cmap(ci), label=cname)
    ax.legend(fontsize=9, markerscale=2)
    ax.set_title('VideoMAE Token Space — All Val Videos by Category', fontsize=12)
    ax.axis('off')
    plt.tight_layout()
    plt.savefig('/content/results/umap_static.png', dpi=150, bbox_inches='tight')
    plt.show()

    # Pick video with all N_TIME temporal positions represented
    unique_vids, counts = np.unique(all_vids, return_counts=True)
    gif_vi = unique_vids[counts == N_TIME][0]
    vid_mask = all_vids == gif_vi
    vid_emb  = emb[vid_mask]      # (N_TIME, 2)
    vid_times = all_times[vid_mask]
    order     = np.argsort(vid_times)
    vid_emb   = vid_emb[order]    # ordered t=0..N_TIME-1
    gif_cat   = IDX_TO_MAIN[val_fc[gif_vi]['main_cat_idx']]
    gif_vid_id = val_fc[gif_vi]['videoid']

    # Decode actual video frames for inset
    vid_row    = subset_df[subset_df['videoid']==gif_vid_id]
    gif_frames = None
    if len(vid_row) > 0:
        gif_frames = decode_clip(vid_row.iloc[0]['resolved_path'],
                                  n_frames=N_TIME, img_size=96)

    GIF_PATH   = Path('/content/results/trajectory.gif')
    bg_mask    = ~vid_mask
    gif_images = []

    for fi in range(N_TIME):
        fig, axes = plt.subplots(1, 2, figsize=(12, 5),
                                  gridspec_kw={'width_ratios': [2, 1]})
        ax = axes[0]

        # Grey background
        ax.scatter(emb[bg_mask,0], emb[bg_mask,1],
                   s=5, alpha=0.15, color='lightgray', zorder=1)
        # Full trajectory (faded)
        ax.plot(vid_emb[:,0], vid_emb[:,1],
                color=cmap(MAIN_TO_IDX.get(gif_cat,0)),
                alpha=0.25, lw=1, zorder=2)
        # Past frames as coloured dots with arrows
        if fi > 0:
            ax.scatter(vid_emb[:fi,0], vid_emb[:fi,1], s=35, alpha=0.6,
                       color=cmap(MAIN_TO_IDX.get(gif_cat,0)), zorder=3)
            for si in range(fi):
                ax.annotate('', xy=vid_emb[si+1], xytext=vid_emb[si],
                    arrowprops=dict(arrowstyle='->', lw=1.2, alpha=0.5,
                                    color=cmap(MAIN_TO_IDX.get(gif_cat,0))),
                    zorder=4)

        # Context / target split indicator
        ax.axvline(vid_emb[CTX_T-1,0] if fi >= CTX_T else np.nan,
                   color='navy', ls=':', lw=1, alpha=0.5,
                   label='ctx→tgt split' if fi==CTX_T else '')

        # Current frame: red star
        colour = 'red' if fi < CTX_T else 'darkgreen'
        label  = f'Frame {fi+1}/{N_TIME} ({"context" if fi<CTX_T else "TARGET"})'
        ax.scatter(vid_emb[fi,0], vid_emb[fi,1], s=200,
                   color=colour, marker='*', zorder=5, label=label)
        ax.legend(fontsize=8, loc='upper right')
        ax.set_title(f'VideoMAE Latent Trajectory — {gif_cat}', fontsize=11)
        ax.axis('off')

        # Inset: actual video frame
        if gif_frames is not None and fi < len(gif_frames):
            axes[1].imshow(gif_frames[fi])
        axes[1].set_title(f'Frame {fi+1}  '
                          f'({"context" if fi<CTX_T else "TARGET"})\n'
                          f'{gif_vid_id}', fontsize=9)
        axes[1].axis('off')

        plt.suptitle('VideoMAE Temporal Latent Space Trajectory',
                     fontsize=12, fontweight='bold')
        plt.tight_layout()
        fig.canvas.draw()
        buf = np.frombuffer(fig.canvas.buffer_rgba(), dtype=np.uint8)
        w, h = fig.canvas.get_width_height()
        gif_images.append(buf.reshape(h, w, 4)[:,:,:3])
        plt.close(fig)

    imageio.mimsave(str(GIF_PATH), gif_images, fps=2, loop=0)
    print(f'GIF saved: {GIF_PATH}')
    from IPython.display import Image as IPImage
    display(IPImage(str(GIF_PATH)))

except Exception as e:
    import traceback; traceback.print_exc()

print('=' * 62)
print('   LATENT MASKED VIDEO PREDICTION — Corrected Results')
print('=' * 62)
print(f'  Backbone                   : VideoMAE ViT-B')
print(f'  Mask ratio                 : {MASK_RATIO*100:.0f}% of context tokens')
print(f'  Context/Target split       : {CTX_T}/{TGT_T} temporal positions')
print(f'  Best training loss         : {best_loss:.4f}')
print()
print('  Reconstruction (normalised, ∈ [0,2]):')
print(f'    Mean recon residual      : {R["recon_res"].mean():.4f}')
print()
print('  Future prediction (normalised, ∈ [0,2]):')
print(f'    Mean future residual     : {R["future_res"].mean():.4f}')
print(f'    Predictor cosine sim     : {R["future_cos"].mean():.4f}')
print(f'    Copy-context baseline    : {R["copy_cos"].mean():.4f}')
print(f'    Improvement over copy    : {R["improvement"].mean():.4f}  ← key metric')
print()
print('  Linear probe (one sample per video, no leakage):')
print(f'    Predicted future reps    : {acc*100:.1f}%  (random={100/N_MAIN:.1f}%)')
print(f'    Raw encoder reps         : {acc_raw*100:.1f}%')
print(f'    Sub-category (raw)       : {acc2*100:.1f}%  (random={100/len(le):.1f}%)')
print('=' * 62)

with open('/content/results/summary_fixed.json', 'w') as f:
    json.dump({
        'recon_res'    : float(R['recon_res'].mean()),
        'future_res'   : float(R['future_res'].mean()),
        'predictor_cos': float(R['future_cos'].mean()),
        'copy_cos'     : float(R['copy_cos'].mean()),
        'improvement'  : float(R['improvement'].mean()),
        'main_acc_pred': float(acc),
        'main_acc_raw' : float(acc_raw),
        'sub_acc_raw'  : float(acc2),
    }, f, indent=2)
print('Saved to /content/results/summary_fixed.json')



class UnmaskedVideoDataset(Dataset):
    """
    Each sample:
      ctx_tokens : (CTX_N, D)  ALL context tokens — nothing hidden
      tgt_tokens : (TGT_N, D)  target frame tokens
      main_cat   : int
    """

    def __init__(self, cache, samples_per_video=8):
        self.cache             = cache
        self.samples_per_video = samples_per_video
        self._build_index()

    def _build_index(self):
        self.samples = []
        for vi in range(len(self.cache)):
            for _ in range(self.samples_per_video):
                self.samples.append(vi)
        random.shuffle(self.samples)

    def __len__(self): return len(self.samples)

    def __getitem__(self, idx):
        vi  = self.samples[idx]
        e   = self.cache[vi]
        tok = e['tokens']          # (N_TOK, D)
        return {
            'ctx_tokens': tok[:CTX_N],     # (CTX_N, D) — full context
            'tgt_tokens': tok[CTX_N:],     # (TGT_N, D)
            'main_cat'  : e['main_cat_idx'],
            'sub_cat'   : e['sub_cat'],
        }


train_ds_unmasked = UnmaskedVideoDataset(train_fc, samples_per_video=8)
val_ds_unmasked   = UnmaskedVideoDataset(val_fc,   samples_per_video=4)

train_loader_unmasked = DataLoader(
    train_ds_unmasked, batch_size=16, shuffle=True,
    num_workers=2, pin_memory=True, drop_last=True
)
val_loader_unmasked = DataLoader(
    val_ds_unmasked, batch_size=16, shuffle=False,
    num_workers=2, pin_memory=True
)

print(f'Unmasked train pairs : {len(train_ds_unmasked)}')
print(f'Unmasked val   pairs : {len(val_ds_unmasked)}')

# Verify batch shapes
b = next(iter(train_loader_unmasked))
print(f'ctx_tokens : {b["ctx_tokens"].shape}  (B, CTX_N={CTX_N}, D={ENC_D})')
print(f'tgt_tokens : {b["tgt_tokens"].shape}  (B, TGT_N={TGT_N}, D={ENC_D})')



class UnmaskedTemporalPredictor(nn.Module):
    """
    Input  : full context tokens (CTX_N, D)
    Output : predicted target frame tokens (TGT_N, D)

    Architecture mirrors LatentMaskPredictor but without mask/recon tokens.
    Uses the same pred_dim, n_heads, n_layers for a fair comparison.
    """

    def __init__(self, enc_dim, pred_dim, n_heads, n_layers, ctx_n, tgt_n):
        super().__init__()
        self.ctx_n   = ctx_n
        self.tgt_n   = tgt_n

        self.in_proj = nn.Linear(enc_dim, pred_dim)

        # Learnable future query tokens — one per target position
        self.future_token = nn.Parameter(torch.randn(1, tgt_n, pred_dim) * 0.02)

        # Positional encoding over full sequence
        self.pos_enc = PositionalEncoding(pred_dim, max_len=ctx_n + tgt_n + 16)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=pred_dim, nhead=n_heads,
            dim_feedforward=pred_dim * 4,
            dropout=0.0, batch_first=True, norm_first=True
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=n_layers)
        self.norm        = nn.LayerNorm(pred_dim)
        self.future_head = nn.Linear(pred_dim, enc_dim)

        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.trunc_normal_(m.weight, std=0.02)
                if m.bias is not None: nn.init.zeros_(m.bias)

    def forward(self, ctx_tokens):
        B   = ctx_tokens.shape[0]
        pe  = self.pos_enc.pe                # (max_len, d)

        ctx_pos = torch.arange(self.ctx_n, device=ctx_tokens.device)
        fut_pos = torch.arange(self.ctx_n, self.ctx_n + self.tgt_n,
                              device=ctx_tokens.device)

        ctx = self.in_proj(ctx_tokens) + pe[ctx_pos].unsqueeze(0)   # (B, CTX_N, d)

        fut = self.future_token.expand(B, -1, -1).clone()
        fut = fut + pe[fut_pos].unsqueeze(0)                         # (B, TGT_N, d)

        x = torch.cat([ctx, fut], dim=1)
        x = self.norm(self.transformer(x))

        return self.future_head(x[:, self.ctx_n:, :])
predictor_unmasked = UnmaskedTemporalPredictor(
    enc_dim  = ENC_D,
    pred_dim = 512,     # same as masked predictor
    n_heads  = 8,       # same
    n_layers = 4,       # same
    ctx_n    = CTX_N,
    tgt_n    = TGT_N,
).to(DEVICE)

n_unmasked = sum(p.numel() for p in predictor_unmasked.parameters())
n_masked   = sum(p.numel() for p in predictor.parameters())
print(f'Unmasked predictor params : {n_unmasked/1e6:.2f} M')
print(f'Masked   predictor params : {n_masked/1e6:.2f} M')
print(f'(should be similar for a fair comparison)')

# Smoke test
b   = next(iter(train_loader_unmasked))
_c  = b['ctx_tokens'].to(DEVICE)
_o  = predictor_unmasked(_c)
print(f'Output shape : {_o.shape}  (B, TGT_N={TGT_N}, D={ENC_D})')


def future_only_loss(future_pred, future_tgt):
    B, Nt, D = future_pred.shape
    fp = F.normalize(future_pred.reshape(B*Nt, D), dim=-1)
    ft = F.normalize(future_tgt.reshape(B*Nt, D),  dim=-1)
    loss = F.mse_loss(fp, ft)
    return loss, {'future': loss.item()}


N_EPOCHS_ABL  = 60
BASE_LR_ABL   = 1e-4
WEIGHT_DECAY  = 1e-4
WARMUP_EPOCHS = 8

optimizer_abl   = torch.optim.AdamW(
    predictor_unmasked.parameters(),
    lr=BASE_LR_ABL, weight_decay=WEIGHT_DECAY
)
total_steps_abl  = N_EPOCHS_ABL * len(train_loader_unmasked)
warmup_steps_abl = WARMUP_EPOCHS * len(train_loader_unmasked)

def lr_abl(step):
    if step < warmup_steps_abl:
        return BASE_LR_ABL * step / max(1, warmup_steps_abl)
    p = (step - warmup_steps_abl) / max(1, total_steps_abl - warmup_steps_abl)
    return 1e-6 + (BASE_LR_ABL - 1e-6) * 0.5 * (1 + math.cos(math.pi * p))


history_abl    = defaultdict(list)
best_loss_abl  = float('inf')
global_step    = 0

print('Training unmasked predictor ...')
print(f'Epochs: {N_EPOCHS_ABL} | Steps/epoch: {len(train_loader_unmasked)}')
print('─' * 55)

for epoch in range(N_EPOCHS_ABL):
    predictor_unmasked.train()
    train_ds_unmasked._build_index()
    ep_loss  = 0.
    ep_comps = defaultdict(float)

    for batch in train_loader_unmasked:
        ctx = batch['ctx_tokens'].to(DEVICE)
        tgt = batch['tgt_tokens'].to(DEVICE)
        for pg in optimizer_abl.param_groups: pg['lr'] = lr_abl(global_step)

        future_pred = predictor_unmasked(ctx)
        loss, comps = future_only_loss(future_pred, tgt)

        optimizer_abl.zero_grad()
        loss.backward()
        nn.utils.clip_grad_norm_(predictor_unmasked.parameters(), 1.0)
        optimizer_abl.step()

        ep_loss += loss.item()
        for k, v in comps.items(): ep_comps[k] += v
        global_step += 1

    n   = len(train_loader_unmasked)
    avg = ep_loss / n
    history_abl['epoch'].append(epoch)
    history_abl['loss'].append(avg)
    history_abl['lr'].append(lr_abl(global_step))
    history_abl['future'].append(ep_comps['future'] / n)

    if epoch % 10 == 0 or epoch == N_EPOCHS_ABL - 1:
        print(f'[{epoch:3d}/{N_EPOCHS_ABL}] loss={avg:.4f}  '
              f'lr={lr_abl(global_step):.2e}')

    if avg < best_loss_abl:
        best_loss_abl = avg
        torch.save(
            {'epoch': epoch, 'state': predictor_unmasked.state_dict(), 'loss': avg},
            '/content/checkpoints/best_unmasked.pt'
        )

print(f'\nDone. Best loss (unmasked): {best_loss_abl:.4f}')

ckpt_abl = torch.load('/content/checkpoints/best_unmasked.pt', map_location=DEVICE)
predictor_unmasked.load_state_dict(ckpt_abl['state'])
predictor_unmasked.eval()
print(f"Unmasked best  epoch={ckpt_abl['epoch']}  loss={ckpt_abl['loss']:.4f}")


@torch.no_grad()
def extract_unmasked_results(loader):
    out = defaultdict(list)
    for batch in loader:
        ctx = batch['ctx_tokens'].to(DEVICE)  # (B, CTX_N, D)
        tgt = batch['tgt_tokens'].to(DEVICE)  # (B, TGT_N, D)
        B, Nt, D = tgt.shape

        future_pred = predictor_unmasked(ctx)   # (B, TGT_N, D)

        # Normalised future residual
        fp_n = F.normalize(future_pred.reshape(B*Nt, D), dim=-1).reshape(B, Nt, D)
        ft_n = F.normalize(tgt.reshape(B*Nt, D),          dim=-1).reshape(B, Nt, D)
        future_res = (fp_n - ft_n).norm(dim=-1).mean(dim=-1)   # (B,) ∈ [0,2]

        # Directional cosine similarity and improvement
        ctx_mean  = ctx.mean(dim=1)
        tgt_mean  = tgt.mean(dim=1)
        pred_mean = future_pred.mean(dim=1)
        actual_dir = tgt_mean - ctx_mean
        pred_dir   = pred_mean - ctx_mean
        future_cos  = F.cosine_similarity(pred_dir, actual_dir, dim=-1)
        copy_cos    = F.cosine_similarity(
            torch.zeros_like(ctx_mean), actual_dir, dim=-1
        )
        improvement = future_cos - copy_cos

        out['ctx_r'].append(ctx_mean.cpu().float().numpy())
        out['future_res'].append(future_res.cpu().numpy())
        out['future_cos'].append(future_cos.cpu().numpy())
        out['copy_cos'].append(copy_cos.cpu().numpy())
        out['improvement'].append(improvement.cpu().numpy())
        out['main_cat'].append(batch['main_cat'].numpy())
        out['sub_cat'].append(np.array(batch['sub_cat']))

    return {k: np.concatenate(v) for k, v in out.items()}


R_abl     = extract_unmasked_results(val_loader_unmasked)
cat_abl   = R_abl['main_cat']

print('─' * 55)
print('  Unmasked predictor results')
print('─' * 55)
print(f'  Future residual  : {R_abl["future_res"].mean():.4f}')
print(f'  Predictor cosine : {R_abl["future_cos"].mean():.4f}')
print(f'  Copy baseline    : {R_abl["copy_cos"].mean():.4f}')
print(f'  Improvement      : {R_abl["improvement"].mean():.4f}')


masked_imp   = R['improvement']       # from main notebook
unmasked_imp = R_abl['improvement']
masked_res   = R['future_res']
unmasked_res = R_abl['future_res']
masked_cos   = R['future_cos']
unmasked_cos = R_abl['future_cos']

print('=' * 58)
print('   ABLATION: Masked vs Unmasked Predictor')
print('=' * 58)
print(f'  Metric                  Masked    Unmasked  Δ')
print('─' * 58)
print(f'  Future residual       : {masked_res.mean():.4f}    '
      f'{unmasked_res.mean():.4f}    '
      f'{unmasked_res.mean()-masked_res.mean():+.4f}')
print(f'  Predictor cosine      : {masked_cos.mean():.4f}    '
      f'{unmasked_cos.mean():.4f}    '
      f'{unmasked_cos.mean()-masked_cos.mean():+.4f}')
print(f'  Improvement over copy : {masked_imp.mean():.4f}    '
      f'{unmasked_imp.mean():.4f}    '
      f'{unmasked_imp.mean()-masked_imp.mean():+.4f}')
print('=' * 58)

delta = masked_imp.mean() - unmasked_imp.mean()
if delta > 0.02:
    print(f'\n✅ Masking HELPS by {delta:.3f} — supports the JEPA argument.')
    print('   Partial observation forces richer temporal representations.')
elif delta > -0.02:
    print(f'\n⚖️  Masking has negligible effect ({delta:+.3f}).')
    print('   The temporal structure alone drives prediction, not the masking.')
else:
    print(f'\n⚠️  Masking HURTS by {abs(delta):.3f}.')
    print('   Removing context information degrades future prediction.')

# Statistical significance: Mann-Whitney U test
from scipy import stats
stat, pval = stats.mannwhitneyu(
    masked_imp, unmasked_imp, alternative='greater'
)
print(f'\nMann-Whitney U (masked > unmasked): p={pval:.4f}')
if pval < 0.05:
    print('  Statistically significant (p<0.05) — masking genuinely improves prediction.')
else:
    print('  Not significant — difference may be due to variance.')

fig, axes = plt.subplots(2, 3, figsize=(18, 10))

axes[0,0].hist(masked_imp,   bins=30, alpha=0.6, color='steelblue',
               edgecolor='white', label=f'Masked  (mean={masked_imp.mean():.3f})')
axes[0,0].hist(unmasked_imp, bins=30, alpha=0.6, color='darkorange',
               edgecolor='white', label=f'Unmasked (mean={unmasked_imp.mean():.3f})')
axes[0,0].axvline(masked_imp.mean(),   c='steelblue',  lw=2, ls='--')
axes[0,0].axvline(unmasked_imp.mean(), c='darkorange', lw=2, ls='--')
axes[0,0].axvline(0, c='gray', lw=1, ls=':')
axes[0,0].set(xlabel='Improvement over copy-context baseline')
axes[0,0].set_title('Improvement Distribution\nMasked vs Unmasked')
axes[0,0].legend(); axes[0,0].grid(alpha=0.3)

axes[0,1].hist(masked_res,   bins=30, alpha=0.6, color='steelblue',
               edgecolor='white', label=f'Masked  (mean={masked_res.mean():.3f})')
axes[0,1].hist(unmasked_res, bins=30, alpha=0.6, color='darkorange',
               edgecolor='white', label=f'Unmasked (mean={unmasked_res.mean():.3f})')
axes[0,1].axvline(masked_res.mean(),   c='steelblue',  lw=2, ls='--')
axes[0,1].axvline(unmasked_res.mean(), c='darkorange', lw=2, ls='--')
axes[0,1].set(xlabel='Normalised future residual ∈ [0,2]')
axes[0,1].set_title('Future Prediction Residual\nMasked vs Unmasked')
axes[0,1].legend(); axes[0,1].grid(alpha=0.3)

axes[0,2].hist(masked_cos,   bins=30, alpha=0.6, color='steelblue',
               edgecolor='white', label=f'Masked  (mean={masked_cos.mean():.3f})')
axes[0,2].hist(unmasked_cos, bins=30, alpha=0.6, color='darkorange',
               edgecolor='white', label=f'Unmasked (mean={unmasked_cos.mean():.3f})')
axes[0,2].axvline(masked_cos.mean(),   c='steelblue',  lw=2, ls='--')
axes[0,2].axvline(unmasked_cos.mean(), c='darkorange', lw=2, ls='--')
axes[0,2].set(xlabel='Cosine similarity with actual future direction')
axes[0,2].set_title('Future Direction Cosine Similarity\nMasked vs Unmasked')
axes[0,2].legend(); axes[0,2].grid(alpha=0.3)

data_masked   = [masked_imp[R['main_cat']==i]   for i in range(N_MAIN)]
data_unmasked = [unmasked_imp[cat_abl==i]        for i in range(N_MAIN)]
data_masked   = [d for d in data_masked   if len(d) > 0]
data_unmasked = [d for d in data_unmasked if len(d) > 0]
labels_used   = [cat_names[i] for i in range(N_MAIN)
                 if len(masked_imp[R['main_cat']==i]) > 0]

x   = np.arange(len(labels_used))
w   = 0.35
for ci, (dm, du) in enumerate(zip(data_masked, data_unmasked)):
    axes[1,0].bar(x[ci] - w/2, dm.mean(),   w, color='steelblue',
                  alpha=0.8, label='Masked'   if ci==0 else '')
    axes[1,0].bar(x[ci] + w/2, du.mean(),   w, color='darkorange',
                  alpha=0.8, label='Unmasked' if ci==0 else '')
    axes[1,0].errorbar(x[ci] - w/2, dm.mean(), yerr=dm.std(),
                       fmt='none', c='black', capsize=4, lw=1.5)
    axes[1,0].errorbar(x[ci] + w/2, du.mean(), yerr=du.std(),
                       fmt='none', c='black', capsize=4, lw=1.5)
axes[1,0].axhline(0, c='gray', ls='--', lw=1)
axes[1,0].set_xticks(x); axes[1,0].set_xticklabels(labels_used, rotation=20)
axes[1,0].set(ylabel='Mean improvement over copy-context')
axes[1,0].set_title('Per-Category Improvement\nMasked vs Unmasked')
axes[1,0].legend(); axes[1,0].grid(alpha=0.3)

ep_main = history['epoch']
ep_abl  = history_abl['epoch']
axes[1,1].plot(ep_main, history['loss'],      lw=2, c='steelblue',  label='Masked (total)')
axes[1,1].plot(ep_main, history['future'],    lw=1.5, c='steelblue',
               ls='--', alpha=0.6, label='Masked (future only)')
axes[1,1].plot(ep_abl,  history_abl['loss'],  lw=2, c='darkorange', label='Unmasked')
axes[1,1].set(xlabel='Epoch', ylabel='Loss')
axes[1,1].set_title('Training Loss Curves')
axes[1,1].legend(); axes[1,1].grid(alpha=0.3)

metrics   = ['Future\nResidual↓', 'Predictor\nCosine↑', 'Improvement\nover Copy↑']
vals_m    = [masked_res.mean(),   masked_cos.mean(),   masked_imp.mean()]
vals_u    = [unmasked_res.mean(), unmasked_cos.mean(), unmasked_imp.mean()]
x2        = np.arange(len(metrics))
bars_m    = axes[1,2].bar(x2 - w/2, vals_m, w, color='steelblue',  alpha=0.8, label='Masked')
bars_u    = axes[1,2].bar(x2 + w/2, vals_u, w, color='darkorange', alpha=0.8, label='Unmasked')
axes[1,2].set_xticks(x2); axes[1,2].set_xticklabels(metrics)
axes[1,2].set_title('Summary: Key Metrics')
axes[1,2].legend(); axes[1,2].grid(alpha=0.3, axis='y')
# Annotate bars
for bar in list(bars_m) + list(bars_u):
    h = bar.get_height()
    axes[1,2].text(bar.get_x() + bar.get_width()/2, h + 0.005,
                   f'{h:.3f}', ha='center', va='bottom', fontsize=8)

plt.suptitle('Ablation: Masked vs Unmasked Context Predictor',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('/content/results/ablation_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

fig, axes = plt.subplots(1, N_MAIN, figsize=(5*N_MAIN, 5), sharey=True)
if N_MAIN == 1: axes = [axes]

for ci, cname in enumerate(cat_names):
    m_data = masked_imp[R['main_cat'] == ci]
    u_data = unmasked_imp[cat_abl == ci]
    if len(m_data) == 0: continue

    axes[ci].violinplot([m_data, u_data], positions=[0, 1], showmedians=True)
    axes[ci].set_xticks([0, 1])
    axes[ci].set_xticklabels(['Masked', 'Unmasked'], fontsize=9)
    axes[ci].axhline(0, c='red', ls='--', lw=1)
    axes[ci].set_title(f'{cname}\nm={m_data.mean():.3f} vs {u_data.mean():.3f}',
                       fontsize=10)
    axes[ci].grid(alpha=0.3)

axes[0].set_ylabel('Improvement over copy-context')
plt.suptitle('Per-Category Improvement Distribution\nMasked vs Unmasked',
             fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig('/content/results/ablation_per_category.png', dpi=150, bbox_inches='tight')
plt.show()

from scipy import stats

stat, pval = stats.mannwhitneyu(
    masked_imp, unmasked_imp, alternative='greater'
)

ablation_results = {
    'masked': {
        'future_res'  : float(masked_res.mean()),
        'predictor_cos': float(masked_cos.mean()),
        'improvement' : float(masked_imp.mean()),
        'best_loss'   : float(best_loss),
    },
    'unmasked': {
        'future_res'  : float(unmasked_res.mean()),
        'predictor_cos': float(unmasked_cos.mean()),
        'improvement' : float(unmasked_imp.mean()),
        'best_loss'   : float(best_loss_abl),
    },
    'delta_improvement': float(masked_imp.mean() - unmasked_imp.mean()),
    'mann_whitney_p'   : float(pval),
    'significant'      : bool(pval < 0.05),
    'per_category': {
        cat_names[i]: {
            'masked_improvement'  : float(masked_imp[R['main_cat']==i].mean())
                                    if (R['main_cat']==i).sum() > 0 else None,
            'unmasked_improvement': float(unmasked_imp[cat_abl==i].mean())
                                    if (cat_abl==i).sum() > 0 else None,
        }
        for i in range(N_MAIN)
    }
}

with open('/content/results/ablation_results.json', 'w') as f:
    json.dump(ablation_results, f, indent=2)

print('=' * 58)
print('   ABLATION FINAL SUMMARY')
print('=' * 58)
print(f'  Masked improvement   : {masked_imp.mean():.4f}')
print(f'  Unmasked improvement : {unmasked_imp.mean():.4f}')
print(f'  Delta (masked-unmask): {masked_imp.mean()-unmasked_imp.mean():+.4f}')
print(f'  Mann-Whitney p-value : {pval:.4f}')
print(f'  Significant (p<0.05) : {pval < 0.05}')
print('─' * 58)
print('  Per-category delta (masked - unmasked):')
for i, cname in enumerate(cat_names):
    m = masked_imp[R['main_cat']==i]
    u = unmasked_imp[cat_abl==i]
    if len(m) > 0 and len(u) > 0:
        print(f'    {cname:20s}: {m.mean()-u.mean():+.4f}')
print('=' * 58)
print('Results saved to /content/results/ablation_results.json')

